apiVersion: v1
kind: Secret
metadata:
  name: shaikgpt-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "YOUR_API_KEY"  # Replace with your actual OpenAI key
  DATABASE_URL: "postgresql://shaik:shaik@postgres:5432/shaikgpt"
