apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-sample
  name: pod-sample
spec:
  containers:
  - image: nginx
    name: pod-sample
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
